### ISSUE TITLE
V3.0?

### ISSUE THREAD

**Issue by afeno** [Mickaelh51/Arduino-Oregon-Library#1]
Excellent work Mickael! It is working fine on my first try. :)
I noticed that it is only working with the sensors V2. For example the THN132N.

Is it suppose to work with the sensors V3?  (THGR810)

Thank you.
Best Regards,
Alfredo.

**Comment by Mickaelh51** [comment]
Hi Alfredo.
thanks for your thanks ;)
I don't know if it work with V3. I'm sorry.
Now, I use this product: http://www.nemcon.nl/blog2/ (it's more powerfull)

bye


2017-03-12 14:40 GMT+01:00 afeno <notifications@github.com>:
