### ISSUE TITLE
oregon with esp32

### ISSUE THREAD

**Issue by robademar** [Mickaelh51/Arduino-Oregon-Library#3]
I tried to use the library with esp32 but I couldn't define properly the interrupt pin. Should something being changed in the library ? Thanks

**Comment by Mickaelh51** [comment]
Hi, I'm sorry i don't use this library anymore. i'm using this now:
http://www.rflink.nl/blog2/

Bye

**Comment by robademar** [comment]
many thanks, but unfortunately this doesn't suport esp32.I'll look around for somthing else.
Giovanni Roberto Mariani 

    Il martedì 9 ottobre 2018, 19:40:09 CEST, HUBERT MICKAEL <notifications@github.com> ha scritto:  
 
 Hi, I'm sorry i don't use this library anymore. i'm using this now:
http://www.rflink.nl/blog2/

Bye
